### ISSUE TITLE
Enhancer annotation hdf5 issue

### ISSUE THREAD

**Issue by gonzalobenegas** [frederikkemarin/BEND#46]
Thank you for your help again. I'm running into an issue precomputing embeddings for `enhancer_annotation` task (saw some online suggestions about possible file corruption).

```bash
(BEND) gbenegas@luthien:/scratch/users/gbenegas/projects/BEND$ python scripts/precompute_embeddings.py model=resnetlm task=enhancer_annotation
Run Embedding
[2023-10-23 18:01:56,193][HYDRA] Launching 1 jobs locally
[2023-10-23 18:01:56,193][HYDRA]        #0 : model=resnetlm task=enhancer_annotation
Embedding data for enhancer_annotation
Embedding with resnetlm
Embedding split: part2
         Embedding chunk 0 (1/1)
Error executing job with overrides: ['model=resnetlm', 'task=enhancer_annotation']
Traceback (most recent call last):
  File "/scratch/users/gbenegas/projects/BEND/scripts/precompute_embeddings.py", line 49, in run_experiment
    sequtils.embed_from_bed(**cfg[cfg.task], embedder = embedder,
  File "/scratch/users/gbenegas/projects/BEND/bend/io/sequtils.py", line 119, in embed_from_bed
    hdf5_file = h5py.File(hdf5_file, mode = "r")['labels'] if hdf5_file else None
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/scratch/users/gbenegas/software/mambaforge/envs/BEND/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: 'Unable to synchronously open object (bad local heap signature)'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by frederikkemarin** [comment]
Hello, 
Yes this particular file was corrupted. It has been replaced on the [erda directory ](https://sid.erda.dk/share_redirect/aNQa0Oz2lY/data/enhancer_annotation/enhancer_annotation.hdf5) and will be replaced on zenodo soon as well.

**Comment by fteufel** [comment]
Fixed version now also on zenodo

**Comment by gonzalobenegas** [comment]
Thank you!
